version: '2'
services:
  yakariweb01:
    build: .
    ports:
      - "8880:80"
  yakariweb02:
    build: .
    ports:
      - "8881:80"
  yakariweb03:
    build: .
    ports:
      - "8882:80"
  yakariweb04:
    build: .
    ports:
      - "8883:80"
